language: node_js
node_js:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17 
  - 18
script:
  - npm run ci
after_script:
  - npm i coverage
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
